### ISSUE TITLE
Sharpsign-whitespace is invalid

### ISSUE THREAD

**Issue by Harleqin** [jingtaozf/literate-lisp#1]
Sharpsign-whitespace is specified to be always invalid.  See http://clhs.lisp.se/Body/02_dhu.htm.

Maybe use a different character?

**Comment by jingtaozf** [comment]
This reader syntax is only valid in an org file, and we also change the meaning of reader syntax for "#+".
Can you give me some examples which will raise issues for current design?

Or are there a better design for it?

Thanks.

**Comment by Harleqin** [comment]
Hmmm.  I may be misreading the Spec here: the section I linked to describes standard syntax, but you are free to use a modified readtable that overrides anything.

Yeah, sorry, I retract my concern.
