### ISSUE TITLE
Failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [jingtaozf/literate-lisp#11]
Building with SBCL 2.0.9.5-442f54894 / ASDF 3.3.1 for quicklisp dist creation.

Commit id e039ef0ff30a7eaa50447dbe134162bce5ac876e

*literate-demo* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Package 5AM does not exist. Line: 219, Column: 9, File-Position: 11619 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/literate-lisp/d987e4919a57cdabdcae7349909b9841e2c80853/literate-lisp-20201006-git/readme.org" {100712DB03}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A50103}>: COMPILE-FILE-ERROR while compiling #<ORG "literate-demo" "demo" "readme">

```

[Full log here](http://report.quicklisp.org/2020-10-06/failure-report/literate-lisp.html)

**Comment by jingtaozf** [comment]
Thanks very much, it has been fixed in the latest commit: https://github.com/jingtaozf/literate-lisp/commit/6598d10940c08e3d72738d20583dd144444260fe
