### ISSUE TITLE
slime+sbcl refers to wrong points in org files

### ISSUE THREAD

**Issue by akater** [jingtaozf/literate-lisp#2]
I'm not sure if this is an SBCL issue, a SLIME issue, or a suboptimal implementation of `*org-readtable*`, or if I should have used different src block keywords.

Minimal working example of an org file:

```org
# a sharp-space

* Compiles OK
but takes the blame for [[undefined]]
#+begin_src lisp :tangle yes :results none
'compiles-ok-but-takes-the-blame
#+end_src

* Dummy block
#+begin_src lisp :tangle no :results none :eval never
'dummy-expression
#+end_src

* Erroneous block
#+name: undefined
#+begin_src lisp :tangle yes :results none
error
#+end_src
```

In Slime REPL:

```lisp
(defvar *prev-readtables* nil)
(push *readtable* *prev-readtables* )
(setq *readtable* literate-lisp::*org-readtable* )
```

Now, `slime-compile-file` the org file. Compiler's warning “undefined variable: ERROR” will refer to the `end_src` under first src block.

`slime-edit-definition` jumps to the wrong (previous) `:tangle yes` src block as well. (Not evident in this example.)

**Comment by jingtaozf** [comment]
It should a behavior of SBCL, you can try a lisp file containing following codes:
```lisp
;; 1 comment
'compiles-ok-but-takes-the-blame
;; 2 comment
'dummy-expression
;; 3 comment
;; 4 comment
error
```
The error note line will be in the line contains `3 comment`.
