### ISSUE TITLE
source inside org examples and comments is not ignored 

### ISSUE THREAD

**Issue by alanruttenberg** [jingtaozf/literate-lisp#5]
For the below org, M-x org-babel-execute-buffer does not evaluate anything, but literate-lisp does. I believe these should be ignored.

```org
#+begin_example
#+begin_src lisp
(print 'hello)
#+end_src
#+end_example

#+begin_comment
#+begin_src lisp
(print 'hello)
#+end_src
#+end_comment
```

**Comment by jingtaozf** [comment]
org-babel-execute-buffer  is not the protocol we want to keep compatibility because at least for me, I never use it when I do literate programming.

But a patch to avoid such confusion is welcome.
