### ISSUE TITLE
Is it possible to use literate-lisp to make a package-inferred system?

### ISSUE THREAD

**Issue by svetlyak40wt** [jingtaozf/literate-lisp#7]
I like to use package inferred feature of ASDF.

Is it possible to use literate-lisp?

**Comment by jingtaozf** [comment]
If you check the source code of ASDF, you'll find that it will only probe lisp files:
https://github.com/fare/asdf/blob/master/package-inferred-system.lisp
(search "lisp" in this file to locate the related lines)

So to make ASDF support literate-lisp, we have to write some  codes in literate-lisp to extend the behaviour of ASDF so it can probe org files.

A patch to literate-lisp is welcome.

**Comment by jingtaozf** [comment]
It is possible soon,
Now literate-lisp has added supported for this feature:
https://github.com/jingtaozf/literate-lisp/blob/master/literate-lisp.org#the-support-for-the-asdf-package-inferred-system-extension

But ASDF has a bug to fix before supporting it correctly:
https://gitlab.common-lisp.net/asdf/asdf/-/issues/34

Please update both literate-lisp and ASDF to the latest version if you want to have a try.

**Comment by jingtaozf** [comment]
Or you can try this ASDF versin berfore it got updated in official site:
https://github.com/jingtaozf/asdf

**Comment by jingtaozf** [comment]
Please upgrade to ASDF 3.3.4.5 and the latest literate-lisp.

**Comment by svetlyak40wt** [comment]
Thank you very much, @jingtaozf. Will try this ASAP.
